runtime: python27
api_version: 1
threadsafe: true
handlers:
    - url: /(.*\.(js|css|svg|png)(|\.map))$
      static_files: dist/\1
      upload: dist/Cafe-Mambo-Dashboard/(.*)(|\.map)
    - url: /.*
      static_files: dist/Cafe-Mambo-Dashboard/index.html
      upload: dist/Cafe-Mambo-Dashboard/.*

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
